// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntkzwdvssgrqbvtzhgxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50a3p3ZHZzc2dycWJ2dHpoZ3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzYxMTIsImV4cCI6MjA1OTI1MjExMn0.DysE_zgDdeLp2dP7_uIuLtGLAX8pnj2pZCkWl9ElGxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);